/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        gold: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        dark: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        }
      },
      backgroundColor: {
        'light-primary': '#f8fafc',
        'light-secondary': '#ffffff',
        'light-accent': '#f1f5f9',
        'light-card': '#f8fafc',
        'light-surface': '#ffffff',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'slide-up': 'slideUp 0.5s ease-out',
        'fade-in': 'fadeIn 0.6s ease-out',
        'lightning': 'lightning 2s ease-in-out infinite',
        'spark': 'spark 1.5s ease-in-out infinite',
        'electric-pulse': 'electricPulse 3s ease-in-out infinite',
        'lightning-flash': 'lightningFlash 4s ease-in-out infinite',
        'spark-random': 'sparkRandom 3s ease-in-out infinite',
        'ambient-glow': 'ambientGlow 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 20px #0ea5e9' },
          '100%': { boxShadow: '0 0 30px #0ea5e9, 0 0 40px #0ea5e9' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        lightning: {
          '0%': { opacity: '0.3' },
          '10%': { opacity: '1' },
          '15%': { opacity: '0.4' },
          '20%': { opacity: '0.9' },
          '25%': { opacity: '0.2' },
          '30%': { opacity: '0.8' },
          '35%': { opacity: '0.1' },
          '40%': { opacity: '0.7' },
          '50%': { opacity: '0.3' },
          '60%': { opacity: '0.9' },
          '70%': { opacity: '0.2' },
          '80%': { opacity: '0.6' },
          '90%': { opacity: '0.1' },
          '100%': { opacity: '0.3' },
        },
        lightningFlash: {
          '0%': { opacity: '0' },
          '2%': { opacity: '1' },
          '4%': { opacity: '0' },
          '6%': { opacity: '0.8' },
          '8%': { opacity: '0' },
          '10%': { opacity: '0.9' },
          '12%': { opacity: '0' },
          '100%': { opacity: '0' },
        },
        spark: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(0.8)' },
          '50%': { opacity: '0.9', transform: 'scale(1.1)' },
        },
        sparkRandom: {
          '0%': { opacity: '0', transform: 'scale(0)' },
          '10%': { opacity: '1', transform: 'scale(1.2)' },
          '15%': { opacity: '0', transform: 'scale(0.8)' },
          '20%': { opacity: '0.7', transform: 'scale(1)' },
          '25%': { opacity: '0', transform: 'scale(0)' },
          '100%': { opacity: '0', transform: 'scale(0)' },
        },
        electricPulse: {
          '0%, 100%': { opacity: '0.4', filter: 'brightness(1)' },
          '50%': { opacity: '1', filter: 'brightness(1.5)' },
        },
        ambientGlow: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.1)' },
        },
        flowRight: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateX(calc(100vw + 10px))', opacity: '0' },
        },
        flowDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateY(calc(100vh + 10px))', opacity: '0' },
        },
        flowDiagonal: {
          '0%': { transform: 'translate(-10px, -10px)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translate(calc(100vw + 10px), calc(100vh + 10px))', opacity: '0' },
        },
        floatRandom: {
          '0%, 100%': { transform: 'translate(0, 0) scale(0.8)', opacity: '0.3' },
          '25%': { transform: 'translate(20px, -15px) scale(1)', opacity: '0.7' },
          '50%': { transform: 'translate(-10px, -25px) scale(1.1)', opacity: '1' },
          '75%': { transform: 'translate(-25px, 10px) scale(0.9)', opacity: '0.6' },
        },
      },
    },
  },
  plugins: [],
};