import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'cs';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.made': 'Made by Smooth',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.badge': 'Professional Development Solutions — Brno & Czech Republic',
    'hero.title.line1': 'Website & E-shop Development',
    'hero.title.line2': 'from Brno for all of Czechia',
    'hero.subtitle': 'We build custom websites, e-shops, and systems.\nWe diagnose and repair computers.\nWe build every project with a focus on performance, a clean approach, and long-term reliability.',
    'hero.cta.services': 'Explore Services',
    'hero.cta.start': 'Schedule Free Consultation',
    'hero.stats.projects': 'Projects Delivered',
    'hero.stats.experience': 'Years Experience',
    'hero.stats.support': 'Support Available',
    
    // Services Section
    'services.badge': 'Our Services',
    'services.title': 'Comprehensive Tech Solutions',
    'services.subtitle': 'Every project begins with understanding your goal.\nWhether you need a website, e-shop, or internal system, we focus on results that help your business grow — for clients in Brno and across the Czech Republic.',
    'services.section.software.title': 'Software Development',
    'services.section.software.subtitle': 'Custom digital products built to help your business grow — websites, e-shops, apps, and systems.',
    'services.section.hardware.title': 'Hardware & IT Service',
    'services.section.hardware.subtitle': 'Repairs, upgrades, and complete PC solutions for individuals and businesses.',
    'services.filter.all': 'All',
    'services.filter.software': 'Software',
    'services.filter.hardware': 'Hardware',
    'services.website.title': 'Website Development',
    'services.website.description': 'Modern, responsive websites built with cutting-edge technologies.',
    'services.website.price': 'from 15,000 CZK',
    'services.website.feature1': 'Responsive Design',
    'services.website.feature2': 'SEO Optimized',
    'services.website.feature3': 'Fast Loading',
    'services.website.feature4': 'Custom CMS',
    'services.ecommerce.title': 'E-shop Development & E-commerce Solutions',
    'services.ecommerce.description': 'Various platforms (Shoptet, PrestaShop, and more) or fully custom development, payment integration, SEO optimization.',
    'services.ecommerce.price': 'from 30,000 CZK',
    'services.ecommerce.feature1': 'Shoptet / PrestaShop',
    'services.ecommerce.feature2': 'Custom Development',
    'services.ecommerce.feature3': 'Payment Integration',
    'services.ecommerce.feature4': 'SEO Optimization',
    'services.mobile.title': 'Mobile Applications',
    'services.mobile.description': 'Cross-platform mobile app development for Android and iOS.',
    'services.mobile.price': 'quote on request',
    'services.mobile.feature1': 'Modern Frameworks',
    'services.mobile.feature2': 'Multi-platform',
    'services.mobile.feature3': 'UX Consultation & Design',
    'services.mobile.feature4': 'Android & iOS',
    'services.database.title': 'Database Systems',
    'services.database.description': 'We create robust database solutions and tools for managing corporate data.',
    'services.database.price': 'quote on request',
    'services.database.feature1': 'System Consulting',
    'services.database.feature2': 'System Development',
    'services.database.feature3': 'Data Analysis',
    'services.database.feature4': 'Enterprise Solutions',
    'services.custom.title': 'Custom Desktop Builds',
    'services.custom.description': 'Gaming and workstation builds to your exact configuration.',
    'services.custom.price': 'Price depends on configuration',
    'services.cta': 'Get a Free Quote',
    'services.cta.card': "I'm Interested",

    // Hardware & IT Service items
    'hw.diagnostics.title': 'PC/Laptop Diagnostics & Repair',
    'hw.diagnostics.description': 'Fault identification, repair, and faulty part replacement — repair cost depends on the extent of the damage.',
    'hw.diagnostics.price': 'from 300 CZK',
    'hw.cleaning.title': 'Cleaning & Maintenance',
    'hw.cleaning.description': 'Dust removal and thermal paste replacement.',
    'hw.cleaning.price': '500 CZK',
    'hw.windowsInstall.title': 'Windows Installation/Reinstallation',
    'hw.windowsInstall.description': 'Clean install, drivers, activation.',
    'hw.windowsInstall.price': '600 CZK',
    'hw.hardwareUpgrade.title': 'Hardware Upgrades',
    'hw.hardwareUpgrade.description': 'RAM, SSD/HDD, GPU replacement or addition for a faster, smoother-running computer.',
    'hw.hardwareUpgrade.price': 'from 400 CZK + parts',
    'hw.virusRemoval.title': 'Virus & Malware Removal',
    'hw.virusRemoval.description': 'System cleanup and security check.',
    'hw.virusRemoval.price': '500–800 CZK',
    'hw.backup.title': 'Backup & Data Transfer',
    'hw.backup.description': 'Safe transfer of documents, photos, and settings from your old PC to a new one.',
    'hw.backup.price': 'from 400 CZK',
    'hw.corpOnboarding.title': 'Corporate PC Onboarding',
    'hw.corpOnboarding.badge': 'Recommended for Businesses',
    'hw.corpOnboarding.description': 'Windows Pro, business software (Office 365, accounting software, VPN), backup solutions, security policies.',
    'hw.corpOnboarding.price': '1,500–2,500 CZK',
    'hw.corpPcSetup.title': 'Complete Corporate PC Procurement',
    'hw.corpPcSetup.badge': 'Turnkey Package',
    'hw.corpPcSetup.description': 'Hardware consultation and selection, warrantied purchase, full setup and configuration.',
    'hw.corpPcSetup.price': 'consultation 500–1,000 CZK + hardware + setup',

    // About Section
    'about.badge': 'About Us',
    'about.title.crafting': 'Your Vision.',
    'about.title.excellence': 'Our Code.',
    'about.description': 'We are a duo based in Brno, united by a passion for technology, design, and innovation, building for clients across the Czech Republic.\nAt Smooth Development, we create solutions that combine aesthetics, performance, and usability.\nOur goal is for the digital world to run smoothly — just like your business.\nThrough a combination of technical knowledge and a sensitive approach to detail, we transform ideas into reality.',
    'about.expertise.title': 'Full-Stack Expertise',
    'about.expertise.description': 'End-to-end development from frontend interface to backend systems and databases.',
    'about.custom.title': 'Custom Solutions',
    'about.custom.description': 'Applications and systems designed precisely for your business needs.',
    'about.hardware.title': 'Hardware Services',
    'about.hardware.description': 'Professional repairs, upgrades, and custom computer builds for maximum performance.',
    'about.cta': 'Let\'s Work Together',
    'about.achievement.expert.title': 'Expert Team',
    'about.achievement.expert.description': 'Certified professionals with years of industry experience',
    'about.achievement.client.title': 'Client-Focused',
    'about.achievement.client.description': 'Dedicated to understanding and exceeding client expectations',
    'about.achievement.timely.title': 'Timely Delivery',
    'about.achievement.timely.description': 'Consistent track record of on-time project completion',
    'about.achievement.quality.title': 'Quality Assurance',
    'about.achievement.quality.description': 'Rigorous testing and quality control processes',
    
    // Contact Section
    'contact.badge': 'Get In Touch',
    'contact.title.ready': 'Ready for a',
    'contact.title.project': 'Digital Shift?',
    'contact.subtitle': 'Reach out to us and together we\'ll find a way to transform your ideas into modern, functional solutions.\nThe consultation is free – getting started is easy.',
    'contact.phone': 'Phone',
    'contact.phone.hours': 'Mon-Fri 9AM-6PM',
    'contact.email': 'Email',
    'contact.email.support': '24/7 Support Available',
    'contact.location': 'Location',
    'contact.location.value': 'Brno, Czech Republic',
    'contact.location.services': 'Remote & On-site Services',
    'contact.response': 'Response Time',
    'contact.response.time': 'Within 24 hours',
    'contact.response.note': 'Usually much faster!',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.service': 'Service of Interest',
    'contact.form.service.select': 'Select a service',
    'contact.form.service.website': 'Website Development',
    'contact.form.service.ecommerce': 'E-commerce Solution',
    'contact.form.service.mobile': 'Mobile Application',
    'contact.form.service.database': 'Database System',
    'contact.form.service.diagnostics': 'PC/Laptop Diagnostics',
    'contact.form.service.cleaning': 'Cleaning & Maintenance',
    'contact.form.service.windowsInstall': 'Windows Installation',
    'contact.form.service.hardwareUpgrade': 'Hardware Upgrade',
    'contact.form.service.virusRemoval': 'Virus/Malware Removal',
    'contact.form.service.backup': 'Backup & Data Transfer',
    'contact.form.service.custom': 'Custom Desktop Build',
    'contact.form.service.corpOnboarding': 'Corporate PC Onboarding',
    'contact.form.service.corpPcSetup': 'Complete Corporate PC Procurement',
    'contact.form.service.consultation': 'Consultation',
    'contact.form.message': 'Project Description',
    'contact.form.message.placeholder': 'Tell us about your project, requirements, timeline, and any specific details...',
    'contact.form.send': 'Send Message',
    'contact.form.success': 'Thank you for your message! We\'ll get back to you soon.',
    
    // Footer
    'footer.tagline': 'Full-stack development agency crafting digital excellence.',
    'footer.description': 'Expert full-stack development, custom applications, e-commerce solutions, and professional tech services. Transform your business with cutting-edge technology.',
    'footer.services': 'Services',
    'footer.links': 'Quick Links',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Smooth Development. All rights reserved.',

    // Made by Smooth Page
    'made.title': 'Made by Smooth',
    'made.subtitle': 'Every project is a partnership for us.\nFrom concept to deployment – every step we take aims to achieve perfection in design, performance, and usability.',
    'made.project1.title': 'Autoškola JEDU! Brno',
    'made.project1.description': 'A small driving school in Brno with a friendly, family atmosphere — Category B courses and refresher lessons.',
    'made.aqms.title': 'AQMS — Quality Management System',
    'made.aqms.description': 'Full-stack quality management application built for manufacturing environments. Modeled on real-world automotive supply chain QMS processes — 8D problem solving, CAPA, deviation approvals, and traceability. Built from scratch on a custom PHP MVC architecture without any framework, demonstrating core backend fundamentals: routing, ORM-free data access, and session-based authorization.',
    'made.smoothpost.title': 'SmoothPost — Social Media Automation',
    'made.smoothpost.description': 'Social media publishing automation tool built in Node.js, using the Anthropic API (Claude) for text generation and OpenAI for image generation. Enables creating and scheduling complete content across platforms without manually crafting each post.',
    'made.project2.title': 'Kadeřnictví POHODA',
    'made.project2.description': 'Website for hairdresser Helena Bošinová in Liberec — 20+ years of experience and online booking.',

    'made.project3.title': 'MN Shine Detailing',
    'made.project3.description': 'Car detailing studio near Brno — interior cleaning, paint renovation, ceramic coating.',
    'made.project4.title': 'Studio Mirage',
    'made.project4.description': 'Accredited requalification courses in Liberec — pedicure, cosmetics, nail design.',
    'made.project5.title': 'Vraky Brno',
    'made.project5.description': 'Vehicle towing, purchase, and eco-friendly disposal in the South Moravian Region.',
    'made.armyshop.title': 'Army Shop Ořechov',
    'made.armyshop.description': 'E-shop for military and outdoor gear built on Shoptet — clothing, footwear, backpacks, and camping equipment. Includes custom graphics: banners, logo, and edited product photos.',
    'made.filter.all': 'All',
    'made.filter.website': 'Websites',
    'made.filter.webapp': 'Web Apps',
    'made.filter.eshop': 'E-shops',
    'made.cta': 'Start Your Project',
    'made.visit': 'Visit website',

    // Homepage: Process Section
    'process.title': 'How We Work Together',
    'process.subtitle': 'No guesswork, no surprises. You always know exactly where your project stands.',
    'process.step1.title': 'Free Consultation',
    'process.step1.description': 'We discuss your idea, goals, and budget.',
    'process.step2.title': 'Proposal & Plan',
    'process.step2.description': 'We prepare a concrete plan, timeline estimate, and cost breakdown.',
    'process.step3.title': 'Design & Visuals',
    'process.step3.description': 'We design the UI/UX and visual identity before a single line of code is written.',
    'process.step4.title': 'Development',
    'process.step4.description': 'We build your project with regular progress updates.',
    'process.step5.title': 'Testing & SEO',
    'process.step5.description': 'We test every feature and fine-tune technical SEO for search visibility.',
    'process.step6.title': 'Approval & Launch',
    'process.step6.description': 'Final sign-off, domain setup, and deployment to production.',
    'process.step7.title': 'Training & Support',
    'process.step7.description': 'We train your team and stay available for ongoing support.',

    // Homepage: Services teaser
    'home.services.title': 'What We Do',
    'home.services.subtitle': 'Custom web, e-shop, and app development is the core of our work. We also offer PC/laptop IT service and repairs.',
    'home.services.hardware.title': 'IT Service & Repairs',
    'home.services.hardware.description': 'Diagnostics, cleaning, upgrades, and repairs for PCs and laptops.',
    'home.services.hardware.badge': 'Also available',
    'home.services.exploreCta': 'Explore all services',

    // Homepage: Work Showcase
    'work.title': 'Our Work',
    'work.subtitle': 'A few examples of what we\'ve been building lately.',
    'work.cta': 'View More Projects',

    // Homepage: Final CTA
    'finalcta.title': "Let's Solve It",
    'finalcta.subtitle': "Let's talk it through, the consultation is free and no-strings-attached.",
    'finalcta.cta': 'Let\'s Get Started',

    // SEO — per-page title/description
    'seo.home.title': 'Smooth Development — Web, E-commerce & App Development + IT Service | Brno',
    'seo.home.description': 'Smooth Development builds custom websites, e-shops, and web applications from Brno. We also offer PC/laptop IT service and repairs.',
    'seo.services.title': 'Services — Web & App Development + PC/IT Service | Smooth Development Brno',
    'seo.services.description': 'Website, e-shop, mobile app, and database development, plus PC and laptop repair, upgrades, and corporate IT service — from Brno for clients across the Czech Republic.',
    'seo.about.title': 'About Us — Full-Stack Development Studio in Brno | Smooth Development',
    'seo.about.description': 'Meet Smooth Development, a full-stack development duo based in Brno delivering websites, e-shops, and custom systems across the Czech Republic.',
    'seo.made.title': 'Made by Smooth — Our Web & E-shop Portfolio | Smooth Development',
    'seo.made.description': 'A selection of websites and e-shops built by Smooth Development for clients in Brno and throughout the Czech Republic.',
    'seo.contact.title': 'Contact — Smooth Development, Brno, Czech Republic',
    'seo.contact.description': 'Get in touch with Smooth Development in Brno for a free consultation on your website, e-shop, or web application — we work with clients across the Czech Republic.',
  },
  cs: {
    // Header
    'nav.home': 'Domů',
    'nav.services': 'Služby',
    'nav.about': 'O nás',
    'nav.made': 'Made by Smooth',
    'nav.contact': 'Kontakt',
    
    // Hero Section
    'hero.badge': 'Profesionální vývojová řešení — Brno & ČR',
    'hero.title.line1': 'Vývoj webových stránek a e‑shopů',
    'hero.title.line2': 'z Brna pro celou ČR',
    'hero.subtitle': 'Vyvíjíme weby, e-shopy a systémy na míru.\nDiagnostikujeme a opravujeme počítače.\nKaždý projekt stavíme s důrazem na výkon, čistý přístup a dlouhodobou spolehlivost.',
    'hero.cta.services': 'Prozkoumat služby',
    'hero.cta.start': 'Domluvte konzultaci zdarma',
    'hero.stats.projects': 'Dokončených projektů',
    'hero.stats.experience': 'Let zkušeností',
    'hero.stats.support': 'Podpora k dispozici',
    
    // Services Section
    'services.badge': 'Naše služby',
    'services.title': 'Komplexní technologická řešení',
    'services.subtitle': 'Každý projekt začínáme pochopením vašeho cíle.\nAť už potřebujete web, e-shop nebo interní systém, zaměřujeme se na výsledek, který pomáhá vašemu podnikání růst — pro klienty v Brně i po celé České republice.',
    'services.section.software.title': 'Softwarová řešení',
    'services.section.software.subtitle': 'Digitální produkty na míru, které pomáhají vašemu podnikání růst — weby, e-shopy, aplikace a systémy.',
    'services.section.hardware.title': 'Hardware a IT servis',
    'services.section.hardware.subtitle': 'Opravy, upgrady a kompletní PC řešení pro jednotlivce i firmy.',
    'services.filter.all': 'Vše',
    'services.filter.software': 'Software',
    'services.filter.hardware': 'Hardware',
    'services.website.title': 'Vývoj webových stránek',
    'services.website.description': 'Moderní, responzivní weby postavené na nejmodernějších technologiích.',
    'services.website.price': 'od 15 000 Kč',
    'services.website.feature1': 'Responzivní design',
    'services.website.feature2': 'SEO optimalizace',
    'services.website.feature3': 'Rychlé načítání',
    'services.website.feature4': 'Vlastní CMS',
    'services.ecommerce.title': 'Vývoj e-shopů a e-commerce řešení',
    'services.ecommerce.description': 'Různé platformy (Shoptet, PrestaShop a další) nebo vývoj na míru, integrace plateb, SEO optimalizace.',
    'services.ecommerce.price': 'od 30 000 Kč',
    'services.ecommerce.feature1': 'Shoptet / PrestaShop',
    'services.ecommerce.feature2': 'Vývoj na míru',
    'services.ecommerce.feature3': 'Integrace plateb',
    'services.ecommerce.feature4': 'SEO optimalizace',
    'services.mobile.title': 'Mobilní aplikace',
    'services.mobile.description': 'Vývoj multiplatformních mobilních aplikací pro Android i iOS.',
    'services.mobile.price': 'dle poptávky',
    'services.mobile.feature1': 'Moderní frameworky',
    'services.mobile.feature2': 'Multi-platform',
    'services.mobile.feature3': 'Konzultace a návrh UX',
    'services.mobile.feature4': 'Android i iOS',
    'services.database.title': 'Databázové systémy',
    'services.database.description': 'Tvoříme robustní databázová řešení a nástroje pro správu firemních dat.',
    'services.database.price': 'dle poptávky',
    'services.database.feature1': 'Systémové poradenství',
    'services.database.feature2': 'Vývoj systémů',
    'services.database.feature3': 'Datová analýza',
    'services.database.feature4': 'Firemní řešení',
    'services.custom.title': 'Sestavy na míru',
    'services.custom.description': 'Herní i pracovní sestavy dle konfigurace.',
    'services.custom.price': 'Cena dle konfigurace',
    'services.cta': 'Nezávazná poptávka',
    'services.cta.card': 'Mám zájem',

    // Hardware a IT servis — jednotlivé položky
    'hw.diagnostics.title': 'Diagnostika a opravy PC/NTB',
    'hw.diagnostics.description': 'Identifikace poruchy, oprava a výměna vadných dílů — cena opravy se odvíjí od rozsahu poškození.',
    'hw.diagnostics.price': 'od 300 Kč',
    'hw.cleaning.title': 'Čištění a údržba',
    'hw.cleaning.description': 'Vyčištění od prachu, výměna teplovodivé pasty.',
    'hw.cleaning.price': '500 Kč',
    'hw.windowsInstall.title': 'Instalace/reinstalace Windows',
    'hw.windowsInstall.description': 'Čistá instalace, ovladače, aktivace.',
    'hw.windowsInstall.price': '600 Kč',
    'hw.hardwareUpgrade.title': 'Hardwarové upgrady',
    'hw.hardwareUpgrade.description': 'RAM, SSD/HDD, GPU výměna nebo přidání pro rychlejší a plynulejší chod počítače.',
    'hw.hardwareUpgrade.price': 'od 400 Kč + díly',
    'hw.virusRemoval.title': 'Odstranění virů a malwaru',
    'hw.virusRemoval.description': 'Čištění systému, kontrola bezpečnosti.',
    'hw.virusRemoval.price': '500–800 Kč',
    'hw.backup.title': 'Zálohování a přenos dat',
    'hw.backup.description': 'Bezpečný přenos dokumentů, fotek i nastavení ze starého PC na nový.',
    'hw.backup.price': 'od 400 Kč',
    'hw.corpOnboarding.title': 'Firemní onboarding PC',
    'hw.corpOnboarding.badge': 'Doporučeno pro firmy',
    'hw.corpOnboarding.description': 'Windows Pro, firemní software (Office 365, účetní SW, VPN), zálohovací řešení, bezpečnostní politiky.',
    'hw.corpOnboarding.price': '1 500–2 500 Kč',
    'hw.corpPcSetup.title': 'Kompletní pořízení PC pro firmu',
    'hw.corpPcSetup.badge': 'Balíček na klíč',
    'hw.corpPcSetup.description': 'Konzultace a výběr hardwaru, nákup se zárukou, plné zprovoznění a nastavení.',
    'hw.corpPcSetup.price': 'konzultace 500–1000 Kč + hardware + zprovoznění',

    // About Section
    'about.badge': 'O nás',
    'about.title.crafting': 'Váš nápad.',
    'about.title.excellence': 'Náš kód.',
    'about.description': 'Jsme dvojice z Brna, kterou spojuje vášeň pro technologie, design a inovace — tvoříme pro klienty po celé České republice.\nVe Smooth Development vytváříme řešení, která spojují estetiku, výkon a použitelnost.\nNaším cílem je, aby digitální svět fungoval hladce — stejně jako vaše podnikání.\nDíky kombinaci technických znalostí a citlivého přístupu k detailům proměňujeme nápady ve skutečnost.',
    'about.expertise.title': 'Full-Stack odbornost',
    'about.expertise.description': 'Komplexní vývoj od frontendového rozhraní po backendové systémy a databáze.',
    'about.custom.title': 'Řešení na míru',
    'about.custom.description': 'Aplikace a systémy navržené přesně podle potřeb vašeho podnikání.',
    'about.hardware.title': 'Hardwarové služby',
    'about.hardware.description': 'Profesionální opravy, upgrady a stavby počítačů na míru pro maximální výkon.',
    'about.cta': 'Pojďme spolupracovat',
    'about.achievement.expert.title': 'Odborný tým',
    'about.achievement.expert.description': 'Profesionálové se zkušenostmi v oboru',
    'about.achievement.client.title': 'Zaměření na klienta',
    'about.achievement.client.description': 'Věnujeme se porozumění a překonávání očekávání klientů',
    'about.achievement.timely.title': 'Včasné dodání',
    'about.achievement.timely.description': 'Konzistentní historie včasného dokončování projektů',
    'about.achievement.quality.title': 'Zajištění kvality',
    'about.achievement.quality.description': 'Důkladné testování a procesy kontroly kvality',
    
    // Contact Section
    'contact.badge': 'Kontaktujte nás',
    'contact.title.ready': 'Připravení na',
    'contact.title.project': 'digitální posun?',
    'contact.subtitle': 'Ozvěte se nám a společně najdeme cestu, jak proměnit vaše nápady v moderní, funkční řešení.\nKonzultace je zdarma – začít je snadné.',
    'contact.phone': 'Telefon',
    'contact.phone.hours': 'Po-Pá 9:00-18:00',
    'contact.email': 'E-mail',
    'contact.email.support': 'Podpora 24/7 k dispozici',
    'contact.location': 'Lokalita',
    'contact.location.value': 'Brno, Česká republika',
    'contact.location.services': 'Vzdálené a místní služby',
    'contact.response': 'Doba odezvy',
    'contact.response.time': 'Do 24 hodin',
    'contact.response.note': 'Obvykle mnohem rychleji!',
    'contact.form.name': 'Celé jméno',
    'contact.form.email': 'E-mailová adresa',
    'contact.form.phone': 'Telefonní číslo',
    'contact.form.service': 'Služba zájmu',
    'contact.form.service.select': 'Vyberte službu',
    'contact.form.service.website': 'Vývoj webových stránek',
    'contact.form.service.ecommerce': 'E-commerce řešení',
    'contact.form.service.mobile': 'Mobilní aplikace',
    'contact.form.service.database': 'Databázový systém',
    'contact.form.service.diagnostics': 'Diagnostika PC/NTB',
    'contact.form.service.cleaning': 'Čištění a údržba',
    'contact.form.service.windowsInstall': 'Instalace Windows',
    'contact.form.service.hardwareUpgrade': 'Hardwarový upgrade',
    'contact.form.service.virusRemoval': 'Odstranění virů/malwaru',
    'contact.form.service.backup': 'Zálohování a přenos dat',
    'contact.form.service.custom': 'Sestava na míru',
    'contact.form.service.corpOnboarding': 'Firemní onboarding PC',
    'contact.form.service.corpPcSetup': 'Kompletní pořízení PC pro firmu',
    'contact.form.service.consultation': 'Konzultace',
    'contact.form.message': 'Popis projektu',
    'contact.form.message.placeholder': 'Řekněte nám o vašem projektu, požadavcích, časovém harmonogramu a jakýchkoli specifických detailech...',
    'contact.form.send': 'Odeslat zprávu',
    'contact.form.success': 'Děkujeme za vaši zprávu! Brzy se vám ozveme.',
    
    // Footer
    'footer.tagline': 'Agentura pro full-stack vývoj. Tvoříme digitální dokonalost.',
    'footer.description': 'Odborný full-stack vývoj, vlastní aplikace, e-commerce řešení a profesionální technické služby. Transformujte své podnikání pomocí nejmodernějších technologií.',
    'footer.services': 'Služby',
    'footer.links': 'Rychlé odkazy',
    'footer.privacy': 'Zásady ochrany osobních údajů',
    'footer.terms': 'Podmínky služby',
    'footer.copyright': '© 2025 Smooth Development. Všechna práva vyhrazena.',

    // Made by Smooth Page
    'made.title': 'Made by Smooth',
    'made.subtitle': 'Každý projekt je pro nás partnerství.\nOd konceptu po nasazení – každý krok děláme s cílem dosáhnout dokonalosti v designu, výkonu i použitelnosti.',
    'made.project1.title': 'Autoškola JEDU! Brno',
    'made.project1.description': 'Malá autoškola s rodinnou atmosférou v Brně — kurzy skupiny B a kondiční jízdy.',
    'made.aqms.title': 'AQMS — systém řízení kvality',
    'made.aqms.description': 'Full-stack aplikace pro řízení kvality navržená pro výrobní prostředí. Modelována podle reálných QMS procesů automobilového průmyslu — 8D řešení problémů, CAPA, schvalování odchylek a sledovatelnost. Postavena od základů na vlastní PHP MVC architektuře bez frameworku — routing, přístup k datům bez ORM a autorizace přes session.',
    'made.smoothpost.title': 'SmoothPost — automatizace sociálních sítí',
    'made.smoothpost.description': 'Nástroj pro automatizaci publikování na sociálních sítích postavený v Node.js s využitím Anthropic API (Claude) pro generování textů a OpenAI pro generování obrázků. Umožňuje vytvářet a plánovat kompletní obsah napříč platformami bez nutnosti manuální tvorby každého příspěvku.',
    'made.project2.title': 'Kadeřnictví POHODA',
    'made.project2.description': 'Web pro kadeřnictví Heleny Bošinové v Liberci — přes 20 let zkušeností a online rezervace termínů.',

    'made.project3.title': 'MN Shine Detailing',
    'made.project3.description': 'Detailingové studio u Brna — čištění interiéru, renovace laku, keramická ochrana.',
    'made.project4.title': 'Studio Mirage',
    'made.project4.description': 'Akreditované rekvalifikační kurzy v Liberci — pedikúra, kosmetika, nehtová designérka.',
    'made.project5.title': 'Vraky Brno',
    'made.project5.description': 'Odtah, výkup a ekologická likvidace vozidel v Jihomoravském kraji.',
    'made.armyshop.title': 'Army Shop Ořechov',
    'made.armyshop.description': 'E-shop s vojenským a outdoorovým vybavením postavený na platformě Shoptet — oblečení, obuv, batohy a kempovací vybavení. Součástí byla i grafika: bannery, logo a úprava produktových fotek.',
    'made.filter.all': 'Vše',
    'made.filter.website': 'Webové stránky',
    'made.filter.webapp': 'Webové aplikace',
    'made.filter.eshop': 'E-shopy',
    'made.cta': 'Začněte váš projekt',
    'made.visit': 'Navštívit web',

    // Homepage: Process Section
    'process.title': 'Jak probíhá spolupráce při vývoji',
    'process.subtitle': 'Žádné nejasnosti, žádná překvapení. Vždy přesně víte, v jaké fázi se váš projekt nachází.',
    'process.step1.title': 'Konzultace zdarma',
    'process.step1.description': 'Probereme váš nápad, cíle a rozpočet. Bez závazků.',
    'process.step2.title': 'Návrh a nabídka',
    'process.step2.description': 'Připravíme konkrétní plán, časový odhad a kalkulaci nákladů.',
    'process.step3.title': 'Design a grafika',
    'process.step3.description': 'Navrhneme UI/UX a vizuální podobu ještě před prvním řádkem kódu.',
    'process.step4.title': 'Vývoj',
    'process.step4.description': 'Stavíme váš projekt s pravidelnými ukázkami postupu.',
    'process.step5.title': 'Testování a SEO',
    'process.step5.description': 'Otestujeme každou funkci a doladíme technické SEO pro lepší viditelnost ve vyhledávání.',
    'process.step6.title': 'Schválení a nasazení',
    'process.step6.description': 'Finální schválení, založení domény a nasazení do provozu.',
    'process.step7.title': 'Zaškolení a podpora',
    'process.step7.description': 'Zaškolíme váš tým a zůstáváme k dispozici i po spuštění.',

    // Homepage: Services teaser
    'home.services.title': 'Co pro vás děláme',
    'home.services.subtitle': 'Vývoj webů, e-shopů a aplikací na míru je jádro naší práce. Nabízíme ale i servis a opravy PC a notebooků.',
    'home.services.hardware.title': 'IT servis a opravy',
    'home.services.hardware.description': 'Diagnostika, čištění, upgrady a opravy PC i notebooků.',
    'home.services.hardware.badge': 'Také nabízíme',
    'home.services.exploreCta': 'Prozkoumat všechny služby',

    // Homepage: Work Showcase
    'work.title': 'Naše práce',
    'work.subtitle': 'Pár ukázek toho, na čem jsme nedávno pracovali.',
    'work.cta': 'Zobrazit více projektů',

    // Homepage: Final CTA
    'finalcta.title': 'Pojďme to vyřešit',
    'finalcta.subtitle': 'Probereme to společně, konzultace je zdarma a nezávazná.',
    'finalcta.cta': 'Napište nám',

    // SEO — titulky a popisky pro jednotlivé stránky
    'seo.home.title': 'Smooth Development — Vývoj webů, e-shopů a aplikací + IT servis | Brno',
    'seo.home.description': 'Smooth Development tvoří weby, e-shopy a webové aplikace na míru z Brna. Doplňkově nabízíme i IT servis a opravy PC a notebooků.',
    'seo.services.title': 'Naše služby — Vývoj webů, e-shopů a IT servis PC | Smooth Development Brno',
    'seo.services.description': 'Vývoj webových stránek, e-shopů, mobilních aplikací a databázových systémů, servis, diagnostika a upgrady PC a notebooků — z Brna pro klienty po celé ČR.',
    'seo.about.title': 'O nás — Full-stack vývojářské studio z Brna | Smooth Development',
    'seo.about.description': 'Poznejte Smooth Development, full-stack vývojářskou dvojici z Brna, která tvoří weby, e-shopy a systémy na míru pro klienty po celé České republice.',
    'seo.made.title': 'Made by Smooth — Portfolio webů a e-shopů | Smooth Development',
    'seo.made.description': 'Výběr webů a e-shopů, které jsme vytvořili pro klienty v Brně i po celé České republice.',
    'seo.contact.title': 'Kontakt — Smooth Development, Brno, Česká republika',
    'seo.contact.description': 'Ozvěte se nám do Brna na nezávaznou konzultaci k vašemu webu, e-shopu nebo webové aplikaci — spolupracujeme s klienty po celé České republice.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'cs';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};